# druid 在 springboot 下的相关配置信息
# https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter/

spring:
  datasource:
    druid:
      one:
        url: jdbc:mysql://localhost:3306/cache?useUnicode=true&characterEncoding=UTF-8
        username: youruname
        password: yourpwd
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 10
        max-wait: 10000
      two:
        url: jdbc:mysql://localhost:3306/cache?useUnicode=true&characterEncoding=UTF-8
        username: youruname
        password: yourpwd
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        max-wait: 20000

